language: node_js 
node_js:
  - "0.12"
cache:
  directories:
  - elm-stuff
  - node_modules
before_script:
  - npm install -g elm@0.18 gulp
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "b3d837c27bde"
  - COMMIT_AUTHOR_EMAIL: "gruszecki.jakub@gmail.com"